// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gajidosen.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	gajidosen.proto

It has these top-level messages:
	AddGajiDosenReq
	ReadGajiDosenByKdGGDosenReq
	ReadGajiDosenByKdGGDosenResp
	ReadGajiDosenResp
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddGajiDosenReq struct {
	KdGGDosen  string `protobuf:"bytes,1,opt,name=KdGGDosen" json:"KdGGDosen,omitempty"`
	JumlahGaji string `protobuf:"bytes,2,opt,name=JumlahGaji" json:"JumlahGaji,omitempty"`
	Keterangan string `protobuf:"bytes,3,opt,name=Keterangan" json:"Keterangan,omitempty"`
	Status     int32  `protobuf:"varint,4,opt,name=Status" json:"Status,omitempty"`
	CreateBy   string `protobuf:"bytes,5,opt,name=CreateBy" json:"CreateBy,omitempty"`
	CreateOn   string `protobuf:"bytes,6,opt,name=CreateOn" json:"CreateOn,omitempty"`
	UpdateBy   string `protobuf:"bytes,7,opt,name=UpdateBy" json:"UpdateBy,omitempty"`
	UpdateOn   string `protobuf:"bytes,8,opt,name=UpdateOn" json:"UpdateOn,omitempty"`
}

func (m *AddGajiDosenReq) Reset()                    { *m = AddGajiDosenReq{} }
func (m *AddGajiDosenReq) String() string            { return proto.CompactTextString(m) }
func (*AddGajiDosenReq) ProtoMessage()               {}
func (*AddGajiDosenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddGajiDosenReq) GetKdGGDosen() string {
	if m != nil {
		return m.KdGGDosen
	}
	return ""
}

func (m *AddGajiDosenReq) GetJumlahGaji() string {
	if m != nil {
		return m.JumlahGaji
	}
	return ""
}

func (m *AddGajiDosenReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *AddGajiDosenReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddGajiDosenReq) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

func (m *AddGajiDosenReq) GetCreateOn() string {
	if m != nil {
		return m.CreateOn
	}
	return ""
}

func (m *AddGajiDosenReq) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *AddGajiDosenReq) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

type ReadGajiDosenByKdGGDosenReq struct {
	KdGGDosen string `protobuf:"bytes,1,opt,name=KdGGDosen" json:"KdGGDosen,omitempty"`
}

func (m *ReadGajiDosenByKdGGDosenReq) Reset()                    { *m = ReadGajiDosenByKdGGDosenReq{} }
func (m *ReadGajiDosenByKdGGDosenReq) String() string            { return proto.CompactTextString(m) }
func (*ReadGajiDosenByKdGGDosenReq) ProtoMessage()               {}
func (*ReadGajiDosenByKdGGDosenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadGajiDosenByKdGGDosenReq) GetKdGGDosen() string {
	if m != nil {
		return m.KdGGDosen
	}
	return ""
}

type ReadGajiDosenByKdGGDosenResp struct {
	KdGGDosen  string `protobuf:"bytes,1,opt,name=KdGGDosen" json:"KdGGDosen,omitempty"`
	JumlahGaji string `protobuf:"bytes,2,opt,name=JumlahGaji" json:"JumlahGaji,omitempty"`
	Keterangan string `protobuf:"bytes,3,opt,name=Keterangan" json:"Keterangan,omitempty"`
	Status     int32  `protobuf:"varint,4,opt,name=Status" json:"Status,omitempty"`
	CreateBy   string `protobuf:"bytes,5,opt,name=CreateBy" json:"CreateBy,omitempty"`
	CreateOn   string `protobuf:"bytes,6,opt,name=CreateOn" json:"CreateOn,omitempty"`
	UpdateBy   string `protobuf:"bytes,7,opt,name=UpdateBy" json:"UpdateBy,omitempty"`
	UpdateOn   string `protobuf:"bytes,8,opt,name=UpdateOn" json:"UpdateOn,omitempty"`
}

func (m *ReadGajiDosenByKdGGDosenResp) Reset()                    { *m = ReadGajiDosenByKdGGDosenResp{} }
func (m *ReadGajiDosenByKdGGDosenResp) String() string            { return proto.CompactTextString(m) }
func (*ReadGajiDosenByKdGGDosenResp) ProtoMessage()               {}
func (*ReadGajiDosenByKdGGDosenResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadGajiDosenByKdGGDosenResp) GetKdGGDosen() string {
	if m != nil {
		return m.KdGGDosen
	}
	return ""
}

func (m *ReadGajiDosenByKdGGDosenResp) GetJumlahGaji() string {
	if m != nil {
		return m.JumlahGaji
	}
	return ""
}

func (m *ReadGajiDosenByKdGGDosenResp) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *ReadGajiDosenByKdGGDosenResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadGajiDosenByKdGGDosenResp) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

func (m *ReadGajiDosenByKdGGDosenResp) GetCreateOn() string {
	if m != nil {
		return m.CreateOn
	}
	return ""
}

func (m *ReadGajiDosenByKdGGDosenResp) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *ReadGajiDosenByKdGGDosenResp) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

type ReadGajiDosenResp struct {
	AllGajiDosen []*ReadGajiDosenByKdGGDosenResp `protobuf:"bytes,1,rep,name=allGajiDosen" json:"allGajiDosen,omitempty"`
}

func (m *ReadGajiDosenResp) Reset()                    { *m = ReadGajiDosenResp{} }
func (m *ReadGajiDosenResp) String() string            { return proto.CompactTextString(m) }
func (*ReadGajiDosenResp) ProtoMessage()               {}
func (*ReadGajiDosenResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadGajiDosenResp) GetAllGajiDosen() []*ReadGajiDosenByKdGGDosenResp {
	if m != nil {
		return m.AllGajiDosen
	}
	return nil
}

func init() {
	proto.RegisterType((*AddGajiDosenReq)(nil), "grpc.AddGajiDosenReq")
	proto.RegisterType((*ReadGajiDosenByKdGGDosenReq)(nil), "grpc.ReadGajiDosenByKdGGDosenReq")
	proto.RegisterType((*ReadGajiDosenByKdGGDosenResp)(nil), "grpc.ReadGajiDosenByKdGGDosenResp")
	proto.RegisterType((*ReadGajiDosenResp)(nil), "grpc.ReadGajiDosenResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for GajiDosenService service

type GajiDosenServiceClient interface {
	AddGajiDosen(ctx context.Context, in *AddGajiDosenReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadGajiDosenByKdGGDosen(ctx context.Context, in *ReadGajiDosenByKdGGDosenReq, opts ...grpc1.CallOption) (*ReadGajiDosenByKdGGDosenResp, error)
	ReadGajiDosen(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadGajiDosenResp, error)
}

type gajiDosenServiceClient struct {
	cc *grpc1.ClientConn
}

func NewGajiDosenServiceClient(cc *grpc1.ClientConn) GajiDosenServiceClient {
	return &gajiDosenServiceClient{cc}
}

func (c *gajiDosenServiceClient) AddGajiDosen(ctx context.Context, in *AddGajiDosenReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.GajiDosenService/AddGajiDosen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gajiDosenServiceClient) ReadGajiDosenByKdGGDosen(ctx context.Context, in *ReadGajiDosenByKdGGDosenReq, opts ...grpc1.CallOption) (*ReadGajiDosenByKdGGDosenResp, error) {
	out := new(ReadGajiDosenByKdGGDosenResp)
	err := grpc1.Invoke(ctx, "/grpc.GajiDosenService/ReadGajiDosenByKdGGDosen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gajiDosenServiceClient) ReadGajiDosen(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadGajiDosenResp, error) {
	out := new(ReadGajiDosenResp)
	err := grpc1.Invoke(ctx, "/grpc.GajiDosenService/ReadGajiDosen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GajiDosenService service

type GajiDosenServiceServer interface {
	AddGajiDosen(context.Context, *AddGajiDosenReq) (*google_protobuf.Empty, error)
	ReadGajiDosenByKdGGDosen(context.Context, *ReadGajiDosenByKdGGDosenReq) (*ReadGajiDosenByKdGGDosenResp, error)
	ReadGajiDosen(context.Context, *google_protobuf.Empty) (*ReadGajiDosenResp, error)
}

func RegisterGajiDosenServiceServer(s *grpc1.Server, srv GajiDosenServiceServer) {
	s.RegisterService(&_GajiDosenService_serviceDesc, srv)
}

func _GajiDosenService_AddGajiDosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGajiDosenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GajiDosenServiceServer).AddGajiDosen(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.GajiDosenService/AddGajiDosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GajiDosenServiceServer).AddGajiDosen(ctx, req.(*AddGajiDosenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GajiDosenService_ReadGajiDosenByKdGGDosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadGajiDosenByKdGGDosenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GajiDosenServiceServer).ReadGajiDosenByKdGGDosen(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.GajiDosenService/ReadGajiDosenByKdGGDosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GajiDosenServiceServer).ReadGajiDosenByKdGGDosen(ctx, req.(*ReadGajiDosenByKdGGDosenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GajiDosenService_ReadGajiDosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GajiDosenServiceServer).ReadGajiDosen(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.GajiDosenService/ReadGajiDosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GajiDosenServiceServer).ReadGajiDosen(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GajiDosenService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.GajiDosenService",
	HandlerType: (*GajiDosenServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddGajiDosen",
			Handler:    _GajiDosenService_AddGajiDosen_Handler,
		},
		{
			MethodName: "ReadGajiDosenByKdGGDosen",
			Handler:    _GajiDosenService_ReadGajiDosenByKdGGDosen_Handler,
		},
		{
			MethodName: "ReadGajiDosen",
			Handler:    _GajiDosenService_ReadGajiDosen_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "gajidosen.proto",
}

func init() { proto.RegisterFile("gajidosen.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x92, 0xcd, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0x29, 0x5f, 0x2f, 0xcc, 0x8b, 0x41, 0x37, 0x11, 0x37, 0x85, 0x18, 0xdc, 0x13, 0xa7,
	0x25, 0xc1, 0xa3, 0x07, 0x23, 0x7e, 0x90, 0xc8, 0xa1, 0x49, 0x89, 0x27, 0x4f, 0x0b, 0x5d, 0x2b,
	0xa4, 0x6c, 0x4b, 0x59, 0x4c, 0xb8, 0xfb, 0x3f, 0x7b, 0xf1, 0x60, 0x76, 0x57, 0xda, 0x62, 0x44,
	0xbc, 0x7b, 0x9c, 0xe7, 0x37, 0xcf, 0x64, 0x66, 0xf2, 0x40, 0xdd, 0x67, 0xb3, 0xa9, 0x17, 0x2e,
	0xb9, 0xa0, 0x51, 0x1c, 0xca, 0x10, 0x15, 0xfd, 0x38, 0x9a, 0xd8, 0x4d, 0x3f, 0x0c, 0xfd, 0x80,
	0x77, 0xb5, 0x36, 0x5e, 0x3d, 0x75, 0xf9, 0x3c, 0x92, 0x6b, 0xd3, 0x42, 0xde, 0x2c, 0xa8, 0x5f,
	0x79, 0xde, 0x80, 0xcd, 0xa6, 0x37, 0xca, 0xe9, 0xf2, 0x05, 0x6a, 0x41, 0x75, 0xe8, 0x0d, 0x06,
	0xba, 0xc6, 0x56, 0xdb, 0xea, 0x54, 0xdd, 0x54, 0x40, 0xa7, 0x00, 0xf7, 0xab, 0x79, 0xc0, 0x9e,
	0x95, 0x07, 0xe7, 0x35, 0xce, 0x28, 0x8a, 0x0f, 0xb9, 0xe4, 0x31, 0x13, 0x3e, 0x13, 0xb8, 0x60,
	0x78, 0xaa, 0xa0, 0x06, 0x94, 0x47, 0x92, 0xc9, 0xd5, 0x12, 0x17, 0xdb, 0x56, 0xa7, 0xe4, 0x7e,
	0x56, 0xc8, 0x86, 0xca, 0x75, 0xcc, 0x99, 0xe4, 0xfd, 0x35, 0x2e, 0x69, 0x57, 0x52, 0xa7, 0xcc,
	0x11, 0xb8, 0x9c, 0x65, 0x8e, 0x50, 0xec, 0x21, 0xf2, 0x8c, 0xef, 0x9f, 0x61, 0x9b, 0x3a, 0x65,
	0x8e, 0xc0, 0x95, 0x2c, 0x73, 0x04, 0xb9, 0x80, 0xa6, 0xcb, 0x59, 0x7a, 0x79, 0x7f, 0x9d, 0xdc,
	0xb8, 0xf7, 0x09, 0xe4, 0x35, 0x0f, 0xad, 0xdd, 0xee, 0x65, 0xf4, 0x47, 0x7e, 0xf8, 0x08, 0x47,
	0x5b, 0x5f, 0xd0, 0xa7, 0xdf, 0x41, 0x8d, 0x05, 0x41, 0xa2, 0x61, 0xab, 0x5d, 0xe8, 0xfc, 0xef,
	0x11, 0xaa, 0xc2, 0x48, 0x7f, 0x7a, 0x9a, 0xbb, 0xe5, 0xeb, 0xbd, 0x5b, 0x70, 0x98, 0x54, 0x23,
	0x1e, 0xbf, 0x4c, 0x27, 0x1c, 0x5d, 0x42, 0x2d, 0x1b, 0x57, 0x74, 0x6c, 0xc6, 0x7e, 0x89, 0xb0,
	0xdd, 0xa0, 0x26, 0xf4, 0x74, 0x13, 0x7a, 0x7a, 0xab, 0x42, 0x4f, 0x72, 0x68, 0x02, 0x78, 0xd7,
	0x0e, 0xe8, 0x6c, 0xdf, 0x8e, 0x0b, 0xfb, 0x17, 0x67, 0x90, 0x1c, 0xea, 0xc3, 0xc1, 0x56, 0x07,
	0xda, 0xb1, 0x8f, 0x7d, 0xf2, 0xcd, 0x38, 0x33, 0x63, 0x5c, 0xd6, 0xad, 0xe7, 0x1f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xab, 0x7d, 0x1d, 0x78, 0xd6, 0x03, 0x00, 0x00,
}
