// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dosen.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	dosen.proto

It has these top-level messages:
	AddDosenReq
	ReadDosenByKdDosenReq
	ReadDosenByKeteranganReq
	ReadDosenByKdDosenResp
	ReadDosenByKeteranganResp
	ReadDosenResp
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddDosenReq struct {
	KdDosen    string `protobuf:"bytes,1,opt,name=KdDosen" json:"KdDosen,omitempty"`
	NamaDosen  string `protobuf:"bytes,2,opt,name=NamaDosen" json:"NamaDosen,omitempty"`
	Keterangan string `protobuf:"bytes,3,opt,name=Keterangan" json:"Keterangan,omitempty"`
	Status     int32  `protobuf:"varint,4,opt,name=Status" json:"Status,omitempty"`
	CreateBy   string `protobuf:"bytes,5,opt,name=CreateBy" json:"CreateBy,omitempty"`
}

func (m *AddDosenReq) Reset()                    { *m = AddDosenReq{} }
func (m *AddDosenReq) String() string            { return proto.CompactTextString(m) }
func (*AddDosenReq) ProtoMessage()               {}
func (*AddDosenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddDosenReq) GetKdDosen() string {
	if m != nil {
		return m.KdDosen
	}
	return ""
}

func (m *AddDosenReq) GetNamaDosen() string {
	if m != nil {
		return m.NamaDosen
	}
	return ""
}

func (m *AddDosenReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *AddDosenReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddDosenReq) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

type ReadDosenByKdDosenReq struct {
	KdDosen string `protobuf:"bytes,1,opt,name=KdDosen" json:"KdDosen,omitempty"`
}

func (m *ReadDosenByKdDosenReq) Reset()                    { *m = ReadDosenByKdDosenReq{} }
func (m *ReadDosenByKdDosenReq) String() string            { return proto.CompactTextString(m) }
func (*ReadDosenByKdDosenReq) ProtoMessage()               {}
func (*ReadDosenByKdDosenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadDosenByKdDosenReq) GetKdDosen() string {
	if m != nil {
		return m.KdDosen
	}
	return ""
}

type ReadDosenByKeteranganReq struct {
	Keterangan string `protobuf:"bytes,1,opt,name=Keterangan" json:"Keterangan,omitempty"`
}

func (m *ReadDosenByKeteranganReq) Reset()                    { *m = ReadDosenByKeteranganReq{} }
func (m *ReadDosenByKeteranganReq) String() string            { return proto.CompactTextString(m) }
func (*ReadDosenByKeteranganReq) ProtoMessage()               {}
func (*ReadDosenByKeteranganReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadDosenByKeteranganReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

type ReadDosenByKdDosenResp struct {
	KdDosen   string `protobuf:"bytes,1,opt,name=KdDosen" json:"KdDosen,omitempty"`
	NamaDosen string `protobuf:"bytes,2,opt,name=NamaDosen" json:"NamaDosen,omitempty"`
	Status    int32  `protobuf:"varint,3,opt,name=Status" json:"Status,omitempty"`
	CreateBy  string `protobuf:"bytes,4,opt,name=CreateBy" json:"CreateBy,omitempty"`
}

func (m *ReadDosenByKdDosenResp) Reset()                    { *m = ReadDosenByKdDosenResp{} }
func (m *ReadDosenByKdDosenResp) String() string            { return proto.CompactTextString(m) }
func (*ReadDosenByKdDosenResp) ProtoMessage()               {}
func (*ReadDosenByKdDosenResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadDosenByKdDosenResp) GetKdDosen() string {
	if m != nil {
		return m.KdDosen
	}
	return ""
}

func (m *ReadDosenByKdDosenResp) GetNamaDosen() string {
	if m != nil {
		return m.NamaDosen
	}
	return ""
}

func (m *ReadDosenByKdDosenResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadDosenByKdDosenResp) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

type ReadDosenByKeteranganResp struct {
	Keterangan string `protobuf:"bytes,1,opt,name=Keterangan" json:"Keterangan,omitempty"`
	NamaDosen  string `protobuf:"bytes,2,opt,name=NamaDosen" json:"NamaDosen,omitempty"`
	Status     int32  `protobuf:"varint,3,opt,name=Status" json:"Status,omitempty"`
	CreateBy   string `protobuf:"bytes,4,opt,name=CreateBy" json:"CreateBy,omitempty"`
}

func (m *ReadDosenByKeteranganResp) Reset()                    { *m = ReadDosenByKeteranganResp{} }
func (m *ReadDosenByKeteranganResp) String() string            { return proto.CompactTextString(m) }
func (*ReadDosenByKeteranganResp) ProtoMessage()               {}
func (*ReadDosenByKeteranganResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadDosenByKeteranganResp) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *ReadDosenByKeteranganResp) GetNamaDosen() string {
	if m != nil {
		return m.NamaDosen
	}
	return ""
}

func (m *ReadDosenByKeteranganResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadDosenByKeteranganResp) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

type ReadDosenResp struct {
	AllDosen []*ReadDosenByKdDosenResp `protobuf:"bytes,1,rep,name=allDosen" json:"allDosen,omitempty"`
}

func (m *ReadDosenResp) Reset()                    { *m = ReadDosenResp{} }
func (m *ReadDosenResp) String() string            { return proto.CompactTextString(m) }
func (*ReadDosenResp) ProtoMessage()               {}
func (*ReadDosenResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadDosenResp) GetAllDosen() []*ReadDosenByKdDosenResp {
	if m != nil {
		return m.AllDosen
	}
	return nil
}

func init() {
	proto.RegisterType((*AddDosenReq)(nil), "grpc.AddDosenReq")
	proto.RegisterType((*ReadDosenByKdDosenReq)(nil), "grpc.ReadDosenByKdDosenReq")
	proto.RegisterType((*ReadDosenByKeteranganReq)(nil), "grpc.ReadDosenByKeteranganReq")
	proto.RegisterType((*ReadDosenByKdDosenResp)(nil), "grpc.ReadDosenByKdDosenResp")
	proto.RegisterType((*ReadDosenByKeteranganResp)(nil), "grpc.ReadDosenByKeteranganResp")
	proto.RegisterType((*ReadDosenResp)(nil), "grpc.ReadDosenResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for DosenService service

type DosenServiceClient interface {
	AddDosen(ctx context.Context, in *AddDosenReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadDosenByKdDosen(ctx context.Context, in *ReadDosenByKdDosenReq, opts ...grpc1.CallOption) (*ReadDosenByKdDosenResp, error)
	ReadDosenByKeterangan(ctx context.Context, in *ReadDosenByKeteranganReq, opts ...grpc1.CallOption) (*ReadDosenByKeteranganResp, error)
	ReadDosen(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadDosenResp, error)
}

type dosenServiceClient struct {
	cc *grpc1.ClientConn
}

func NewDosenServiceClient(cc *grpc1.ClientConn) DosenServiceClient {
	return &dosenServiceClient{cc}
}

func (c *dosenServiceClient) AddDosen(ctx context.Context, in *AddDosenReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.DosenService/AddDosen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dosenServiceClient) ReadDosenByKdDosen(ctx context.Context, in *ReadDosenByKdDosenReq, opts ...grpc1.CallOption) (*ReadDosenByKdDosenResp, error) {
	out := new(ReadDosenByKdDosenResp)
	err := grpc1.Invoke(ctx, "/grpc.DosenService/ReadDosenByKdDosen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dosenServiceClient) ReadDosenByKeterangan(ctx context.Context, in *ReadDosenByKeteranganReq, opts ...grpc1.CallOption) (*ReadDosenByKeteranganResp, error) {
	out := new(ReadDosenByKeteranganResp)
	err := grpc1.Invoke(ctx, "/grpc.DosenService/ReadDosenByKeterangan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dosenServiceClient) ReadDosen(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadDosenResp, error) {
	out := new(ReadDosenResp)
	err := grpc1.Invoke(ctx, "/grpc.DosenService/ReadDosen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DosenService service

type DosenServiceServer interface {
	AddDosen(context.Context, *AddDosenReq) (*google_protobuf.Empty, error)
	ReadDosenByKdDosen(context.Context, *ReadDosenByKdDosenReq) (*ReadDosenByKdDosenResp, error)
	ReadDosenByKeterangan(context.Context, *ReadDosenByKeteranganReq) (*ReadDosenByKeteranganResp, error)
	ReadDosen(context.Context, *google_protobuf.Empty) (*ReadDosenResp, error)
}

func RegisterDosenServiceServer(s *grpc1.Server, srv DosenServiceServer) {
	s.RegisterService(&_DosenService_serviceDesc, srv)
}

func _DosenService_AddDosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDosenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DosenServiceServer).AddDosen(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DosenService/AddDosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DosenServiceServer).AddDosen(ctx, req.(*AddDosenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DosenService_ReadDosenByKdDosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDosenByKdDosenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DosenServiceServer).ReadDosenByKdDosen(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DosenService/ReadDosenByKdDosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DosenServiceServer).ReadDosenByKdDosen(ctx, req.(*ReadDosenByKdDosenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DosenService_ReadDosenByKeterangan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDosenByKeteranganReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DosenServiceServer).ReadDosenByKeterangan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DosenService/ReadDosenByKeterangan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DosenServiceServer).ReadDosenByKeterangan(ctx, req.(*ReadDosenByKeteranganReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DosenService_ReadDosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DosenServiceServer).ReadDosen(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DosenService/ReadDosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DosenServiceServer).ReadDosen(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DosenService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.DosenService",
	HandlerType: (*DosenServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddDosen",
			Handler:    _DosenService_AddDosen_Handler,
		},
		{
			MethodName: "ReadDosenByKdDosen",
			Handler:    _DosenService_ReadDosenByKdDosen_Handler,
		},
		{
			MethodName: "ReadDosenByKeterangan",
			Handler:    _DosenService_ReadDosenByKeterangan_Handler,
		},
		{
			MethodName: "ReadDosen",
			Handler:    _DosenService_ReadDosen_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "dosen.proto",
}

func init() { proto.RegisterFile("dosen.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0x65, 0xf9, 0xf7, 0x83, 0xe1, 0xe7, 0xc1, 0x31, 0x92, 0xba, 0x10, 0x24, 0x7b, 0xe2, 0xb4,
	0x44, 0x3c, 0x68, 0xb8, 0x89, 0x7a, 0x30, 0x24, 0x26, 0x96, 0x9b, 0xb7, 0x05, 0xd6, 0xc6, 0x04,
	0x68, 0x69, 0x17, 0x13, 0xee, 0x5e, 0xfd, 0x00, 0x7e, 0x0d, 0x3f, 0xa1, 0xe9, 0xae, 0x2d, 0xe5,
	0x4f, 0xd1, 0x98, 0x78, 0xdb, 0xd9, 0x37, 0x6f, 0xe6, 0xbd, 0xc9, 0x83, 0xca, 0xd8, 0x0d, 0xe4,
	0x8c, 0x7b, 0xbe, 0xab, 0x5c, 0xcc, 0x3b, 0xbe, 0x37, 0xa2, 0x35, 0xc7, 0x75, 0x9d, 0x89, 0x6c,
	0xeb, 0xbf, 0xe1, 0xe2, 0xa9, 0x2d, 0xa7, 0x9e, 0x5a, 0x9a, 0x16, 0xf6, 0x4e, 0xa0, 0x72, 0x35,
	0x1e, 0xdf, 0x84, 0x2c, 0x5b, 0xce, 0xd1, 0x82, 0x7f, 0x7d, 0x53, 0x59, 0xa4, 0x49, 0x5a, 0x65,
	0x3b, 0x2a, 0xb1, 0x0e, 0xe5, 0x7b, 0x31, 0x15, 0x06, 0xcb, 0x6a, 0x6c, 0xf5, 0x81, 0x0d, 0x80,
	0xbe, 0x54, 0xd2, 0x17, 0x33, 0x47, 0xcc, 0xac, 0x9c, 0x86, 0x13, 0x3f, 0x58, 0x85, 0xe2, 0x40,
	0x09, 0xb5, 0x08, 0xac, 0x7c, 0x93, 0xb4, 0x0a, 0xf6, 0x57, 0x85, 0x14, 0x4a, 0xd7, 0xbe, 0x14,
	0x4a, 0xf6, 0x96, 0x56, 0x41, 0xb3, 0xe2, 0x9a, 0x9d, 0xc1, 0xb1, 0x2d, 0x85, 0x59, 0xdf, 0x5b,
	0xf6, 0x7f, 0x20, 0x92, 0x75, 0xc1, 0x4a, 0x52, 0xe2, 0xfd, 0x21, 0x6b, 0x5d, 0x22, 0xd9, 0x94,
	0xc8, 0x5e, 0x09, 0x54, 0x77, 0xed, 0x0b, 0xbc, 0x5f, 0x5f, 0x65, 0xe5, 0x3a, 0x97, 0xea, 0x3a,
	0xbf, 0xe1, 0xfa, 0x8d, 0xc0, 0x49, 0x8a, 0x87, 0xc0, 0xfb, 0xce, 0xc4, 0x1f, 0xe8, 0xb9, 0x83,
	0x83, 0x58, 0x8e, 0x96, 0x70, 0x09, 0x25, 0x31, 0x99, 0x44, 0xd7, 0xc8, 0xb5, 0x2a, 0x9d, 0x3a,
	0x0f, 0x83, 0xc6, 0x77, 0x1f, 0xcf, 0x8e, 0xbb, 0x3b, 0x1f, 0x59, 0xf8, 0xaf, 0x5f, 0x03, 0xe9,
	0xbf, 0x3c, 0x8f, 0x24, 0x5e, 0x40, 0x29, 0x0a, 0x1f, 0x1e, 0x9a, 0x21, 0x89, 0x30, 0xd2, 0x2a,
	0x37, 0xd1, 0xe5, 0x51, 0x74, 0xf9, 0x6d, 0x18, 0x5d, 0x96, 0xc1, 0x07, 0xc0, 0xed, 0x6d, 0x58,
	0x4b, 0xd7, 0x31, 0xa7, 0x7b, 0x45, 0xb2, 0x0c, 0x3e, 0xae, 0xa7, 0x6d, 0x75, 0xd2, 0xc6, 0x36,
	0x31, 0x99, 0x2b, 0x7a, 0xba, 0x17, 0xd7, 0xb3, 0xbb, 0x50, 0x8e, 0x61, 0x4c, 0x71, 0x45, 0x8f,
	0x36, 0xe6, 0x18, 0xee, 0xb0, 0xa8, 0xdb, 0xce, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x49, 0x1d,
	0x65, 0x33, 0xda, 0x03, 0x00, 0x00,
}
