// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dosen.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	dosen.proto

It has these top-level messages:
	AddDosenReq
	ReadDosenByKdDosenReq
	ReadDosenByKdDosenResp
	ReadDosenResp
	UpdateDosenReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddDosenReq struct {
	KdDosen   string `protobuf:"bytes,1,opt,name=KdDosen" json:"KdDosen,omitempty"`
	NamaDosen string `protobuf:"bytes,2,opt,name=NamaDosen" json:"NamaDosen,omitempty"`
	Status    int32  `protobuf:"varint,3,opt,name=Status" json:"Status,omitempty"`
	CreateBy  string `protobuf:"bytes,4,opt,name=CreateBy" json:"CreateBy,omitempty"`
}

func (m *AddDosenReq) Reset()                    { *m = AddDosenReq{} }
func (m *AddDosenReq) String() string            { return proto.CompactTextString(m) }
func (*AddDosenReq) ProtoMessage()               {}
func (*AddDosenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddDosenReq) GetKdDosen() string {
	if m != nil {
		return m.KdDosen
	}
	return ""
}

func (m *AddDosenReq) GetNamaDosen() string {
	if m != nil {
		return m.NamaDosen
	}
	return ""
}

func (m *AddDosenReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddDosenReq) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

type ReadDosenByKdDosenReq struct {
	KdDosen string `protobuf:"bytes,1,opt,name=KdDosen" json:"KdDosen,omitempty"`
}

func (m *ReadDosenByKdDosenReq) Reset()                    { *m = ReadDosenByKdDosenReq{} }
func (m *ReadDosenByKdDosenReq) String() string            { return proto.CompactTextString(m) }
func (*ReadDosenByKdDosenReq) ProtoMessage()               {}
func (*ReadDosenByKdDosenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadDosenByKdDosenReq) GetKdDosen() string {
	if m != nil {
		return m.KdDosen
	}
	return ""
}

type ReadDosenByKdDosenResp struct {
	KdDosen   string `protobuf:"bytes,1,opt,name=KdDosen" json:"KdDosen,omitempty"`
	NamaDosen string `protobuf:"bytes,2,opt,name=NamaDosen" json:"NamaDosen,omitempty"`
	Status    int32  `protobuf:"varint,3,opt,name=Status" json:"Status,omitempty"`
	CreateBy  string `protobuf:"bytes,4,opt,name=CreateBy" json:"CreateBy,omitempty"`
}

func (m *ReadDosenByKdDosenResp) Reset()                    { *m = ReadDosenByKdDosenResp{} }
func (m *ReadDosenByKdDosenResp) String() string            { return proto.CompactTextString(m) }
func (*ReadDosenByKdDosenResp) ProtoMessage()               {}
func (*ReadDosenByKdDosenResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadDosenByKdDosenResp) GetKdDosen() string {
	if m != nil {
		return m.KdDosen
	}
	return ""
}

func (m *ReadDosenByKdDosenResp) GetNamaDosen() string {
	if m != nil {
		return m.NamaDosen
	}
	return ""
}

func (m *ReadDosenByKdDosenResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadDosenByKdDosenResp) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

type ReadDosenResp struct {
	AllDosen []*ReadDosenByKdDosenResp `protobuf:"bytes,1,rep,name=allDosen" json:"allDosen,omitempty"`
}

func (m *ReadDosenResp) Reset()                    { *m = ReadDosenResp{} }
func (m *ReadDosenResp) String() string            { return proto.CompactTextString(m) }
func (*ReadDosenResp) ProtoMessage()               {}
func (*ReadDosenResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadDosenResp) GetAllDosen() []*ReadDosenByKdDosenResp {
	if m != nil {
		return m.AllDosen
	}
	return nil
}

type UpdateDosenReq struct {
	KdDosen   string `protobuf:"bytes,1,opt,name=KdDosen" json:"KdDosen,omitempty"`
	NamaDosen string `protobuf:"bytes,2,opt,name=NamaDosen" json:"NamaDosen,omitempty"`
	Status    int32  `protobuf:"varint,3,opt,name=Status" json:"Status,omitempty"`
	UpdateBy  string `protobuf:"bytes,4,opt,name=UpdateBy" json:"UpdateBy,omitempty"`
}

func (m *UpdateDosenReq) Reset()                    { *m = UpdateDosenReq{} }
func (m *UpdateDosenReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateDosenReq) ProtoMessage()               {}
func (*UpdateDosenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateDosenReq) GetKdDosen() string {
	if m != nil {
		return m.KdDosen
	}
	return ""
}

func (m *UpdateDosenReq) GetNamaDosen() string {
	if m != nil {
		return m.NamaDosen
	}
	return ""
}

func (m *UpdateDosenReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateDosenReq) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func init() {
	proto.RegisterType((*AddDosenReq)(nil), "grpc.AddDosenReq")
	proto.RegisterType((*ReadDosenByKdDosenReq)(nil), "grpc.ReadDosenByKdDosenReq")
	proto.RegisterType((*ReadDosenByKdDosenResp)(nil), "grpc.ReadDosenByKdDosenResp")
	proto.RegisterType((*ReadDosenResp)(nil), "grpc.ReadDosenResp")
	proto.RegisterType((*UpdateDosenReq)(nil), "grpc.UpdateDosenReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for DosenService service

type DosenServiceClient interface {
	AddDosen(ctx context.Context, in *AddDosenReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadDosenByKdDosen(ctx context.Context, in *ReadDosenByKdDosenReq, opts ...grpc1.CallOption) (*ReadDosenByKdDosenResp, error)
	ReadDosen(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadDosenResp, error)
	UpdateDosen(ctx context.Context, in *UpdateDosenReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type dosenServiceClient struct {
	cc *grpc1.ClientConn
}

func NewDosenServiceClient(cc *grpc1.ClientConn) DosenServiceClient {
	return &dosenServiceClient{cc}
}

func (c *dosenServiceClient) AddDosen(ctx context.Context, in *AddDosenReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.DosenService/AddDosen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dosenServiceClient) ReadDosenByKdDosen(ctx context.Context, in *ReadDosenByKdDosenReq, opts ...grpc1.CallOption) (*ReadDosenByKdDosenResp, error) {
	out := new(ReadDosenByKdDosenResp)
	err := grpc1.Invoke(ctx, "/grpc.DosenService/ReadDosenByKdDosen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dosenServiceClient) ReadDosen(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadDosenResp, error) {
	out := new(ReadDosenResp)
	err := grpc1.Invoke(ctx, "/grpc.DosenService/ReadDosen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dosenServiceClient) UpdateDosen(ctx context.Context, in *UpdateDosenReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.DosenService/UpdateDosen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DosenService service

type DosenServiceServer interface {
	AddDosen(context.Context, *AddDosenReq) (*google_protobuf.Empty, error)
	ReadDosenByKdDosen(context.Context, *ReadDosenByKdDosenReq) (*ReadDosenByKdDosenResp, error)
	ReadDosen(context.Context, *google_protobuf.Empty) (*ReadDosenResp, error)
	UpdateDosen(context.Context, *UpdateDosenReq) (*google_protobuf.Empty, error)
}

func RegisterDosenServiceServer(s *grpc1.Server, srv DosenServiceServer) {
	s.RegisterService(&_DosenService_serviceDesc, srv)
}

func _DosenService_AddDosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDosenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DosenServiceServer).AddDosen(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DosenService/AddDosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DosenServiceServer).AddDosen(ctx, req.(*AddDosenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DosenService_ReadDosenByKdDosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDosenByKdDosenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DosenServiceServer).ReadDosenByKdDosen(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DosenService/ReadDosenByKdDosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DosenServiceServer).ReadDosenByKdDosen(ctx, req.(*ReadDosenByKdDosenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DosenService_ReadDosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DosenServiceServer).ReadDosen(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DosenService/ReadDosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DosenServiceServer).ReadDosen(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DosenService_UpdateDosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDosenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DosenServiceServer).UpdateDosen(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DosenService/UpdateDosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DosenServiceServer).UpdateDosen(ctx, req.(*UpdateDosenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DosenService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.DosenService",
	HandlerType: (*DosenServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddDosen",
			Handler:    _DosenService_AddDosen_Handler,
		},
		{
			MethodName: "ReadDosenByKdDosen",
			Handler:    _DosenService_ReadDosenByKdDosen_Handler,
		},
		{
			MethodName: "ReadDosen",
			Handler:    _DosenService_ReadDosen_Handler,
		},
		{
			MethodName: "UpdateDosen",
			Handler:    _DosenService_UpdateDosen_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "dosen.proto",
}

func init() { proto.RegisterFile("dosen.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xc9, 0x2f, 0x4e,
	0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x96, 0x92, 0x4e,
	0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0xa7, 0xe6, 0x16, 0x94,
	0x54, 0x42, 0x94, 0x28, 0x55, 0x72, 0x71, 0x3b, 0xa6, 0xa4, 0xb8, 0x80, 0x34, 0x05, 0xa5, 0x16,
	0x0a, 0x49, 0x70, 0xb1, 0x7b, 0x43, 0x78, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae,
	0x90, 0x0c, 0x17, 0xa7, 0x5f, 0x62, 0x6e, 0x22, 0x44, 0x8e, 0x09, 0x2c, 0x87, 0x10, 0x10, 0x12,
	0xe3, 0x62, 0x0b, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x96, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0d, 0x82,
	0xf2, 0x84, 0xa4, 0xb8, 0x38, 0x9c, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x9d, 0x2a, 0x25, 0x58, 0xc0,
	0x9a, 0xe0, 0x7c, 0x25, 0x43, 0x2e, 0xd1, 0xa0, 0xd4, 0x44, 0x88, 0xf1, 0x4e, 0x95, 0xde, 0x44,
	0x38, 0x42, 0xa9, 0x85, 0x91, 0x4b, 0x0c, 0x9b, 0x9e, 0xe2, 0x02, 0xba, 0xba, 0xdc, 0x93, 0x8b,
	0x17, 0xee, 0x0a, 0xb0, 0xe5, 0x16, 0x5c, 0x1c, 0x89, 0x39, 0x39, 0x30, 0xdb, 0x99, 0x35, 0xb8,
	0x8d, 0x64, 0xf4, 0x40, 0x61, 0xaf, 0x87, 0xdd, 0xb1, 0x41, 0x70, 0xd5, 0x4a, 0x35, 0x5c, 0x7c,
	0xa1, 0x05, 0x29, 0x89, 0x25, 0xa9, 0xb4, 0x8c, 0x02, 0x88, 0x0d, 0x08, 0x8f, 0xc0, 0xf8, 0x46,
	0x53, 0x99, 0xb8, 0x78, 0xc0, 0xba, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xcc, 0xb9,
	0x38, 0x60, 0xc9, 0x41, 0x48, 0x10, 0xe2, 0x05, 0xa4, 0xe4, 0x21, 0x25, 0xa6, 0x07, 0x49, 0x4b,
	0x7a, 0xb0, 0xb4, 0xa4, 0xe7, 0x0a, 0x4a, 0x4b, 0x4a, 0x0c, 0x42, 0x81, 0x5c, 0x42, 0x98, 0x7e,
	0x15, 0x92, 0xc6, 0x1d, 0x0a, 0x85, 0x52, 0x78, 0x83, 0x48, 0x89, 0x41, 0xc8, 0x8a, 0x8b, 0x13,
	0x2e, 0x27, 0x84, 0xc3, 0x66, 0x29, 0x61, 0x34, 0x43, 0xa0, 0x7a, 0x6d, 0xb9, 0xb8, 0x91, 0x82,
	0x55, 0x48, 0x04, 0xa2, 0x0a, 0x35, 0xa4, 0x71, 0xfb, 0x26, 0x89, 0x0d, 0x2c, 0x62, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x16, 0x6d, 0xd0, 0xbf, 0x4e, 0x03, 0x00, 0x00,
}
