// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dosen.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	dosen.proto

It has these top-level messages:
	AddDosenReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddDosenReq struct {
	KdDosen   string `protobuf:"bytes,1,opt,name=KdDosen" json:"KdDosen,omitempty"`
	NamaDosen string `protobuf:"bytes,2,opt,name=NamaDosen" json:"NamaDosen,omitempty"`
	Status    int32  `protobuf:"varint,3,opt,name=Status" json:"Status,omitempty"`
	CreateBy  string `protobuf:"bytes,4,opt,name=CreateBy" json:"CreateBy,omitempty"`
}

func (m *AddDosenReq) Reset()                    { *m = AddDosenReq{} }
func (m *AddDosenReq) String() string            { return proto.CompactTextString(m) }
func (*AddDosenReq) ProtoMessage()               {}
func (*AddDosenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddDosenReq) GetKdDosen() string {
	if m != nil {
		return m.KdDosen
	}
	return ""
}

func (m *AddDosenReq) GetNamaDosen() string {
	if m != nil {
		return m.NamaDosen
	}
	return ""
}

func (m *AddDosenReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddDosenReq) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

func init() {
	proto.RegisterType((*AddDosenReq)(nil), "grpc.AddDosenReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for DosenService service

type DosenServiceClient interface {
	AddDosen(ctx context.Context, in *AddDosenReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type dosenServiceClient struct {
	cc *grpc1.ClientConn
}

func NewDosenServiceClient(cc *grpc1.ClientConn) DosenServiceClient {
	return &dosenServiceClient{cc}
}

func (c *dosenServiceClient) AddDosen(ctx context.Context, in *AddDosenReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.DosenService/AddDosen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DosenService service

type DosenServiceServer interface {
	AddDosen(context.Context, *AddDosenReq) (*google_protobuf.Empty, error)
}

func RegisterDosenServiceServer(s *grpc1.Server, srv DosenServiceServer) {
	s.RegisterService(&_DosenService_serviceDesc, srv)
}

func _DosenService_AddDosen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDosenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DosenServiceServer).AddDosen(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DosenService/AddDosen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DosenServiceServer).AddDosen(ctx, req.(*AddDosenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DosenService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.DosenService",
	HandlerType: (*DosenServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddDosen",
			Handler:    _DosenService_AddDosen_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "dosen.proto",
}

func init() { proto.RegisterFile("dosen.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xc9, 0x2f, 0x4e,
	0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x96, 0x92, 0x4e,
	0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0xa7, 0xe6, 0x16, 0x94,
	0x54, 0x42, 0x94, 0x28, 0x55, 0x72, 0x71, 0x3b, 0xa6, 0xa4, 0xb8, 0x80, 0x34, 0x05, 0xa5, 0x16,
	0x0a, 0x49, 0x70, 0xb1, 0x7b, 0x43, 0x78, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae,
	0x90, 0x0c, 0x17, 0xa7, 0x5f, 0x62, 0x6e, 0x22, 0x44, 0x8e, 0x09, 0x2c, 0x87, 0x10, 0x10, 0x12,
	0xe3, 0x62, 0x0b, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x96, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0d, 0x82,
	0xf2, 0x84, 0xa4, 0xb8, 0x38, 0x9c, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x9d, 0x2a, 0x25, 0x58, 0xc0,
	0x9a, 0xe0, 0x7c, 0x23, 0x77, 0x2e, 0x1e, 0xb0, 0xe6, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54,
	0x21, 0x73, 0x2e, 0x0e, 0x98, 0x53, 0x84, 0x04, 0xf5, 0x40, 0x4e, 0xd7, 0x43, 0x72, 0x9a, 0x94,
	0x98, 0x1e, 0xc4, 0x1f, 0x7a, 0x30, 0x7f, 0xe8, 0xb9, 0x82, 0xfc, 0xa1, 0xc4, 0x90, 0xc4, 0x06,
	0x16, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x41, 0x78, 0x31, 0x20, 0xfc, 0x00, 0x00, 0x00,
}
